routes/web.php
                Route::get('job-applications/export/{status}/{location}/{startDate}/{endDate}/{jobs}', 'AdminJobApplicationController@export')->name('job-applications.export');
                Route::get('job-applications/data', 'AdminJobApplicationController@data')->name('job-applications.data');
                Route::get('job-applications/table-view', 'AdminJobApplicationController@table')->name('job-applications.table');
                Route::post('job-applications/updateIndex', 'AdminJobApplicationController@updateIndex')->name('job-applications.updateIndex');
                Route::post('job-applications/archive-job-application/{application}', 'AdminJobApplicationController@archiveJobApplication')->name('job-applications.archiveJobApplication');
                Route::post('job-applications/add-skills/{applicationId}', 'AdminJobApplicationController@addSkills')->name('job-applications.addSkills');    
                Route::resource('job-applications', 'AdminJobApplicationController');

                Route::get('applications-archive/data', 'AdminApplicationArchiveController@data')->name('applications-archive.data');
                Route::get('applications-archive/export/{skill}', 'AdminApplicationArchiveController@export')->name('applications-archive.export');
                Route::resource('applications-archive', 'AdminApplicationArchiveController');
    
                Route::get('job-onboard/data', 'AdminJobOnboardController@data')->name('job-onboard.data');
                Route::get('job-onboard/send-offer/{id?}', 'AdminJobOnboardController@sendOffer')->name('job-onboard.send-offer');
                Route::get('job-onboard/update-status/{id?}', 'AdminJobOnboardController@updateStatus')->name('job-onboard.update-status');
                Route::resource('job-onboard', 'AdminJobOnboardController');

                Route::resource('profile', 'AdminProfileController');

                Route::get('interview-schedule/data', 'InterviewScheduleController@data')->name('interview-schedule.data');
                Route::get('interview-schedule/table-view', 'InterviewScheduleController@table')->name('interview-schedule.table-view');
                Route::post('interview-schedule/change-status', 'InterviewScheduleController@changeStatus')->name('interview-schedule.change-status');
                Route::post('interview-schedule/change-status-multiple', 'InterviewScheduleController@changeStatusMultiple')->name('interview-schedule.change-status-multiple');
                Route::get('interview-schedule/notify/{id}/{type}', 'InterviewScheduleController@notify')->name('interview-schedule.notify');
                Route::get('interview-schedule/response/{id}/{type}', 'InterviewScheduleController@employeeResponse')->name('interview-schedule.response');
                Route::resource('interview-schedule', 'InterviewScheduleController');

                Route::get('team/data', 'AdminTeamController@data')->name('team.data');
                Route::post('team/change-role', 'AdminTeamController@changeRole')->name('team.changeRole');
                Route::resource('team', 'AdminTeamController');

                Route::resource('applicant-note', 'ApplicantNoteController');
                Route::resource('sticky-note', 'AdminStickyNotesController');

                Route::resource('departments', 'AdminDepartmentController');

                Route::resource('designations', 'AdminDesignationController');
            });

            Route::get('paypal-recurring', array('as' => 'paypal-recurring','uses' => 'AdminPaypalController@payWithPaypalRecurrring',));
            Route::get('paypal-invoice-download/{id}', array('as' => 'paypal.invoice-download','uses' => 'AdminPaypalController@paypalInvoiceDownload',));

            // route for view/blade file
            Route::get('paywithpaypal', array('as' => 'paywithpaypal','uses' => 'AdminPaypalController@payWithPaypal',));
            // route for post request
            Route::get('paypal/{packageId}/{type}', array('as' => 'paypal','uses' => 'AdminPaypalController@paymentWithpaypal',));
            Route::get('paypal/cancel-subscription', array('as' => 'paypal.cancel-subscription','uses' => 'AdminPaypalController@cancelSubscription',));
            Route::get('paypal/cancel-agreement', array('as' => 'paypal.cancel-agreement','uses' => 'AdminPaypalController@cancelAgreement',));

            // route for check status responce
            Route::get('paypal', array('as' => 'status','uses' => 'AdminPaypalController@getPaymentStatus',));
            Route::get('subscribe/invoice', 'ManageSubscriptionController@invoice')->name('subscribe.invoice');
            Route::get('subscribe/data', 'ManageSubscriptionController@data')->name('subscribe.data');
            Route::get('subscribe/history-data', 'ManageSubscriptionController@historyData')->name('subscribe.history-data');
            Route::get('subscribe/cancel-subscription/{type?}', 'ManageSubscriptionController@cancelSubscription')->name('subscribe.cancel-subscription');
            Route::post('subscribe/payment-stripe', 'ManageSubscriptionController@payment')->name('payments.stripe');
            Route::get('subscribe/select-package/{packageID}',  'ManageSubscriptionController@selectPackage')->name('subscribe.select-package');
            Route::get('subscribe/invoice-download/{invoice}', 'ManageSubscriptionController@download')->name('subscribe.invoice-download');
            Route::get('subscribe/default-invoice-download/{invoice}', 'ManageSubscriptionController@invoiceDownload')->name('subscribe.default-invoice-download');
            Route::get('subscribe/paypal-invoice-download/{id}', array('as' => 'subscribe.paypal-invoice-download','uses' => 'ManageSubscriptionController@paypalInvoiceDownload',));
            Route::get('subscribe/history', array('as' => 'subscribe.history','uses' => 'ManageSubscriptionController@history',));
            Route::get('subscribe/razorpay-invoice-download/{id}', 'ManageSubscriptionController@razorpayInvoiceDownload')->name('subscribe.razorpay-invoice-download');
            Route::post('subscribe/razorpay-payment',  'ManageSubscriptionController@razorpayPayment')->name('subscribe.razorpay-payment');
            Route::post('subscribe/razorpay-subscription',  'ManageSubscriptionController@razorpaySubscription')->name('subscribe.razorpay-subscription');
            Route::resource('subscribe', 'ManageSubscriptionController');

            Route::post('todo-items/update-todo-item', 'AdminTodoItemController@updateTodoItem')->name('todo-items.updateTodoItem');
            Route::resource('todo-items', 'AdminTodoItemController');
        }
    );
    
    Route::group(
        ['namespace' => 'SuperAdmin', 'prefix' => 'super-admin', 'as' => 'superadmin.', 'middleware' => ['super-admin']],
        function () {
            Route::resource('profile', 'SuperAdminProfileController');
            Route::resource('dashboard', 'SuperAdminDashboardController');
            Route::get('smtp-settings/sent-test-email', ['uses' => 'SuperAdminSmtpSettingController@sendTestEmail'])->name('smtp-settings.sendTestEmail');
            Route::resource('smtp-settings', 'SuperAdminSmtpSettingController');

            //language settings
            Route::get('language-settings/change-language', ['uses' => 'LanguageSettingsController@changeLanguage'])->name('language-settings.change-language');
            Route::put('language-settings/change-language-status/{id}', 'LanguageSettingsController@changeStatus')->name('language-settings.changeStatus');
            Route::resource('language-settings', 'LanguageSettingsController');

            Route::resource('theme-settings', 'SuperAdminThemeSettingsController');

            Route::get('update-application/update', ['as' => 'update-application.updateApp', 'uses' => 'UpdateApplicationController@update']);
            Route::get('update-application/download', ['as' => 'update-application.download', 'uses' => 'UpdateApplicationController@download']);
            Route::get('update-application/downloadPercent', ['as' => 'update-application.downloadPercent', 'uses' => 'UpdateApplicationController@downloadPercent']);
            Route::get('update-application/checkIfFileExtracted', ['as' => 'update-application.checkIfFileExtracted', 'uses' => 'UpdateApplicationController@checkIfFileExtracted']);
            Route::get('update-application/install', ['as' => 'update-application.install', 'uses' => 'UpdateApplicationController@install']);
            Route::resource('update-application', 'UpdateApplicationController');


            Route::post('company/updateCompanyPackage/{id}', 'SuperAdminCompanyController@updateCompanyPackage')->name('company.updateCompanyPackage');
            Route::get('company/changePackage/{id}', 'SuperAdminCompanyController@changePackage')->name('company.changePackage');
            Route::get('company/data', 'SuperAdminCompanyController@data')->name('company.data');
            Route::post('company/{id}/login', 'SuperAdminCompanyController@loginAsCompany')->name('company.loginAsCompany');
            Route::resource('company', 'SuperAdminCompanyController');

            Route::resource('global-settings', 'GlobalSettingController');
            Route::get('linkedin-settings/update-status/{id}', 'LinkedInSettingController@updateStatus')->name('updateStatus');
            Route::resource('linkedin-settings', 'LinkedInSettingController');

            Route::get('front-cms/index', ['as' => 'front-cms.index', 'uses' => 'SuperAdminFrontCmsController@index']);
            Route::post('front-cms', ['as' => 'front-cms.updateHeader', 'uses' => 'SuperAdminFrontCmsController@updateHeader']);
            Route::get('front-cms/features', ['as' => 'front-cms.features', 'uses' => 'SuperAdminFrontCmsController@imageFeatures']);

app/Designation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Designation extends Model
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('company', function (Builder $builder) {
            if (auth()->check()) {
                $builder->where('designations.company_id', user()->company_id);
            }
        });
    }
}

resources/views/admin/designation/create.blade.php
<style>
    .hide-box {
        display: none;
    }
</style>
<div class="modal-header">
    <h4 class="modal-title"><i class="icon-plus"></i> @lang('app.designation')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
</div>
<div class="modal-body">
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>@lang('app.designation')</th>
                <th>@lang('app.action')</th>
            </tr>
            </thead>
            <tbody>
            @forelse($designations as $key=>$designation)
                <tr id="desig-{{ $designation->id }}">
                    <td>{{ $key+1 }}</td>
                    <td id="desgName{{ $designation->id }}">{{ ucwords($designation->name) }}</td>
                    <td>
                        <a href="javascript:;" data-dept-id="{{ $designation->id }}" class="btn btn-sm btn-danger btn-rounded delete-designation"><i class="fa fa-times"></i></a>
                        <a href="javascript:;" data-dept-id="{{ $designation->id }}" class="btn btn-sm btn-info btn-rounded edit-designation"><i class="fa fa-pencil"></i> </a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3">@lang('messages.notFound')</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <hr>
    <form id="createDesignation" class="ajax-form" method="post">
        {{ csrf_field() }}
        <div class="form-body">
            <div class="row">
                <div class="col-sm-12 ">
                    <div class="form-group">
                        <label>@lang('app.designation')</label>
                        <input type="text" name="name" id="designation_name" class="form-control">
                        <input type="hidden" name="edit_id" id="edit_id">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="save-designation" class="btn btn-success"> <i class="fa fa-check"></i> @lang('app.save')</button>
            <button type="button" id="update-designation" class="btn btn-success hide-box"> <i class="fa fa-check"></i> @lang('app.update')</button>

        </div>
    </form>

</div>
<div class="modal-footer">
    <button type="button" class="btn dark btn-outline" data-dismiss="modal">@lang('app.close')</button>
</div>


<script>
    // Select 2 init.
    $(".select2").select2({
        formatNoMatches: function () {
            return "{{ __('messages.noRecordFound') }}";
        }
    });

    // Save Interview Schedule
    $('#save-designation').click(function () {
        $.easyAjax({
            url: '{{route('admin.designations.store')}}',
            container: '#createDesignation',
            type: "POST",
            data: $('#createDesignation').serialize(),
            success: function (response) {
                if(response.status == 'success'){
                    var options = [];
                    var rData = [];
                    rData = response.data;
                    $.each(rData, function( index, value ) {
                        var selectData = '';
                        selectData = '<option value="'+value.id+'">'+value.name+'</option>';
                        options.push(selectData);
                    });

                    $('#designation').html(options);
                    $('#designation').select2();
                    $('#addDepartmentModal').modal('hide');
                }
            }
        })
    })

    // Update designation
    $('#update-designation').click(function () {
        var id = $('#edit_id').val();
        var url = "{{ route('admin.designations.update',':id') }}";
        url = url.replace(':id', id);
        var token = '{{ csrf_token() }}';
        var name = $('#designation_name').val();;

        $.easyAjax({
            url: url,
            container: '#createdepartment',
            type: "POST",
            data: {'_token':token, '_method':'PUT','name':name  },
            success: function (response) {
                if(response.status == 'success'){
                    var options = [];
                    var rData = [];
                    rData = response.data;
                    $.each(rData, function( index, value ) {
                        var selectData = '';
                        selectData = '<option value="'+value.id+'">'+value.name+'</option>';
                        options.push(selectData);
                    });

                    $('#designation').html(options);
                    $('#designation').select2();

                    $('#desgName'+id).html(name);// Set name in table row
                    $('#edit_id').val('');// Set edit id field blank
                    $('#designation_name').val('');// Set name field blank
                    $('#update-designation').hide();
                    $('#save-designation').show();
                }
            }
        })
    })

    // Edit department
    $('body').on('click', '.edit-designation', function(){
        var id = $(this).data('dept-id');
        $('#edit_id').val(id);// Set id in edit id field
        $('#designation_name').val($('#desgName'+id).html());// Set name field by edit name
        $('#update-designation').show();
        $('#save-designation').hide();
    });

    // Delete Designation
    $('body').on('click', '.delete-designation', function(){
        var id = $(this).data('dept-id');
        swal({
            title: "@lang('errors.areYouSure')",
            text: "@lang('errors.deleteWarning')",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "@lang('app.delete')",
            cancelButtonText: "@lang('app.cancel')",
            closeOnConfirm: true,
            closeOnCancel: true
        }, function(isConfirm){
            if (isConfirm) {

                var url = "{{ route('admin.designations.destroy',':id') }}";
                url = url.replace(':id', id);

                var token = "{{ csrf_token() }}";

                $.easyAjax({
                    type: 'POST',
                    url: url,
                    data: {'_token': token, '_method': 'DELETE'},
                    success: function (response) {
                        if (response.status == "success") {
                            $.unblockUI();
                            $('#desig-'+id).fadeOut();
                            var options = [];
                            var rData = [];
                            rData = response.data;
                            $.each(rData, function( index, value ) {
                                var selectData = '';
                                selectData = '<option value="'+value.id+'">'+value.name+'</option>';
                                options.push(selectData);
                            });

                            $('#designation').html(options);
                            $('#designation').select2();
                        }
                    }
                });
            }
        });
    });
</script>